environments:
  - name: dev
    configs:  
      endpoints:
        production:
          url: https://services-dev:9443/openweather
        sandbox: 
          url: https://services-dev-sandbox:9443/openweather   
      deploymentEnvironments:
        - displayOnDevportal: true
          deploymentEnvironment: UniversalGW
          deploymentVhost: apim.dev.apis.coach
      policies:
        - Gold

  - name: uat
    configs:
      endpoints:
        production:
          url: https://services-uat:9443/openweather
      deploymentEnvironments:
        - displayOnDevportal: true
          deploymentEnvironment: UniversalGW
          deploymentVhost: apim.uat.apis.coach
      policies:
        - Unlimited
        - Gold